/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current health index
         * @description Returns current health index computed from the latest telemetry snapshot.
         */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/config/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reload health config
         * @description Reloads health_config.yaml without restart.
         */
        get: operations["reload_health_config_api_health_config_reload_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get alerts
         * @description Returns filtered alerts. Both query params optional.
         */
        get: operations["get_alerts_api_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get telemetry history
         * @description Returns telemetry snapshots from the last N minutes.
         */
        get: operations["get_history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export telemetry as CSV
         * @description Returns CSV file as download.
         */
        get: operations["export_history_api_history_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recommendations
         * @description Returns current recommendations based on latest snapshot and health.
         */
        get: operations["get_recommendations_api_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/thresholds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all threshold configs
         * @description Returns all threshold configurations.
         */
        get: operations["get_thresholds_api_config_thresholds_get"];
        /**
         * Update threshold config
         * @description Updates one parameter's thresholds.
         */
        put: operations["update_threshold_api_config_thresholds_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns system health status.
         */
        get: operations["healthz_api_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Switch simulator scenario
         * @description Switch the simulator scenario. Valid values: normal, overheat, brake_failure, low_fuel, highload, demo
         */
        post: operations["set_scenario_api_scenario_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available scenarios
         * @description Returns all available simulator scenarios.
         */
        get: operations["list_scenarios_api_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available routes
         * @description Returns all predefined routes with their stations.
         */
        get: operations["list_routes_api_routes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/route/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start or restart a route
         * @description Resets the simulator position to the first station of the selected route.
         */
        post: operations["start_route_api_route_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/route/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current route status
         * @description Returns the current route progress, active station, and completion status.
         */
        get: operations["route_status_api_route_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertListResponse */
        AlertListResponse: {
            /** Data */
            data: {
                [key: string]: unknown;
            }[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthBreakdown */
        HealthBreakdown: {
            /** Engine */
            engine: number;
            /** Electrical */
            electrical: number;
            /** Brakes */
            brakes: number;
            /** Fuel */
            fuel: number;
        };
        /** HealthCheckResponse */
        HealthCheckResponse: {
            /** Status */
            status: string;
            /** Db */
            db: string;
            /** Simulator */
            simulator: string;
            /** Scenario */
            scenario: string;
            /** Clients */
            clients: number;
        };
        /** HealthFactor */
        HealthFactor: {
            /** Parameter */
            parameter: string;
            /** Impact */
            impact: number;
            /** Status */
            status: string;
        };
        /** HealthIndex */
        HealthIndex: {
            /** Score */
            score: number;
            /** Grade */
            grade: string;
            breakdown: components["schemas"]["HealthBreakdown"];
            /** Topfactors */
            topFactors: components["schemas"]["HealthFactor"][];
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Data */
            data: {
                [key: string]: unknown;
            }[];
        };
        /** MessageResponse */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /** RecommendationListResponse */
        RecommendationListResponse: {
            /** Data */
            data: {
                [key: string]: unknown;
            }[];
        };
        /** RouteSchema */
        RouteSchema: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Stations */
            stations: components["schemas"]["StationSchema"][];
            /** Default */
            default: boolean;
        };
        /** RouteStartResponse */
        RouteStartResponse: {
            /** Message */
            message: string;
            /** Route */
            route: string;
        };
        /** RouteStatusResponse */
        RouteStatusResponse: {
            /** Route Id */
            route_id: string;
            /** Current Station Index */
            current_station_index: number;
            /** Current Station */
            current_station: string;
            /** Next Station */
            next_station: string | null;
            /** Progress */
            progress: number;
            /** Completed */
            completed: boolean;
        };
        /** ScenarioInfo */
        ScenarioInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
        };
        /** ScenarioListResponse */
        ScenarioListResponse: {
            /** Scenarios */
            scenarios: components["schemas"]["ScenarioInfo"][];
        };
        /** ScenarioResponse */
        ScenarioResponse: {
            /** Scenario */
            scenario: string;
            /** Message */
            message: string;
        };
        /** StationSchema */
        StationSchema: {
            /** Name */
            name: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /** ThresholdListResponse */
        ThresholdListResponse: {
            /** Data */
            data: {
                [key: string]: unknown;
            }[];
        };
        /** ThresholdResponse */
        ThresholdResponse: {
            /** Parameter */
            parameter: string;
            /** Minvalue */
            minValue: number;
            /** Maxvalue */
            maxValue: number;
            /** Warningvalue */
            warningValue: number;
            /** Criticalvalue */
            criticalValue: number;
        };
        /** ThresholdUpdateRequest */
        ThresholdUpdateRequest: {
            /** Parameter */
            parameter: string;
            /** Warningvalue */
            warningValue: number;
            /** Criticalvalue */
            criticalValue: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthIndex"];
                };
            };
        };
    };
    reload_health_config_api_health_config_reload_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    get_alerts_api_alerts_get: {
        parameters: {
            query?: {
                /** @description Filter by severity: critical, warning, info */
                severity?: string | null;
                /** @description Max number of alerts to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_api_history_get: {
        parameters: {
            query?: {
                /** @description Number of minutes of history */
                minutes?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_history_api_history_export_get: {
        parameters: {
            query?: {
                /** @description Number of minutes to export */
                minutes?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recommendations_api_recommendations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationListResponse"];
                };
            };
        };
    };
    get_thresholds_api_config_thresholds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThresholdListResponse"];
                };
            };
        };
    };
    update_threshold_api_config_thresholds_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThresholdUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThresholdResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_api_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheckResponse"];
                };
            };
        };
    };
    set_scenario_api_scenario_post: {
        parameters: {
            query: {
                /** @description Scenario name */
                scenario: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_api_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioListResponse"];
                };
            };
        };
    };
    list_routes_api_routes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteSchema"][];
                };
            };
        };
    };
    start_route_api_route_start_post: {
        parameters: {
            query: {
                /** @description Route ID to start */
                route_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_status_api_route_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteStatusResponse"];
                };
            };
        };
    };
}
